Repository Organization-LOOPy/LOOPy-FE, pull requests merged in 2025-07, with the labels that each got.

#9 Feat: login-signup
  Loopy-fe/src/App.tsx
  Loopy-fe/src/assets/images/KakaoLogo.svg
  Loopy-fe/src/assets/images/LoopyIcon.svg
  Loopy-fe/src/components/Input/CommonInput.tsx
  Loopy-fe/src/components/button/CommonButton.tsx
  Loopy-fe/src/layouts/UserLayout.tsx
  Loopy-fe/src/pages/ErrorPage.tsx
  Loopy-fe/src/pages/User/Login/_components/KakaoLogin.tsx
  Loopy-fe/src/pages/User/Login/index.tsx
  Loopy-fe/src/types/svg.d.ts
Labels: feat

#16 Feat: agreement-detail
  Loopy-fe/src/pages/User/Signin/_components/AgreementDetailView.tsx
  Loopy-fe/src/pages/User/Signin/_components/AgreementItem.tsx
  Loopy-fe/src/pages/User/Signin/_components/AgreementListView.tsx
  Loopy-fe/src/pages/User/Signin/_components/AgreementPage.tsx
  Loopy-fe/src/types/agreement.ts
Labels: feat

#18 Style: signin
  Loopy-fe/src/components/Input/CommonInput.tsx
  Loopy-fe/src/components/header/CommonHeader.tsx
  Loopy-fe/src/hooks/useKeyboardOpen.ts
  Loopy-fe/src/hooks/usePasswordValidation.ts
  Loopy-fe/src/hooks/usePhoneVerification.ts
  Loopy-fe/src/pages/User/Login/_components/KakaoLogin.tsx
  Loopy-fe/src/pages/User/Signin/_components/AgreementPage.tsx
  Loopy-fe/src/pages/User/Signin/_components/CheckCircle.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepEmail.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepNickname.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepVerify.tsx
  Loopy-fe/src/pages/User/Signin/index.tsx
  Loopy-fe/src/utils/validation.ts
Labels: feat, style

#20 Feat: map
  Loopy-fe/.env.example
  Loopy-fe/src/assets/images/ArrowDown.svg
  Loopy-fe/src/assets/images/Bookmark.svg
  Loopy-fe/src/assets/images/Filter.svg
  Loopy-fe/src/assets/images/GrabHandle.svg
  Loopy-fe/src/assets/images/ListView.svg
  Loopy-fe/src/assets/images/MapView.svg
  Loopy-fe/src/assets/images/NoStampActiveMarker.svg
  Loopy-fe/src/assets/images/NoStampDefaultMarker.svg
  Loopy-fe/src/assets/images/Reset.svg
  Loopy-fe/src/assets/images/StampActiveMarker.svg
  Loopy-fe/src/assets/images/StampDefaultMarker.svg
  Loopy-fe/src/components/Input/SearchBar.tsx
  Loopy-fe/src/components/button/MapViewToggleButton.tsx
  Loopy-fe/src/components/button/TagButton.tsx
  Loopy-fe/src/components/card/MapCafeDetailCard.tsx
  Loopy-fe/src/components/etc/KeywordTags.tsx
  Loopy-fe/src/components/modal/StampLegend.tsx
  Loopy-fe/src/components/popup/BottomPopup.tsx
  Loopy-fe/src/constants/filterGroup.ts
  Loopy-fe/src/pages/User/Login/index.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterBar.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterDropdownButton.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterIconButton.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterPopup.tsx
  Loopy-fe/src/pages/User/Map/index.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepEmail.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepVerify.tsx
Labels: feat, style

#21 Feat: login signup
  Loopy-fe/src/assets/images/BookMark.svg
  Loopy-fe/src/assets/images/Eye.svg
  Loopy-fe/src/assets/images/EyeOff.svg
  Loopy-fe/src/assets/images/LoopyTitle.svg
  Loopy-fe/src/pages/User/Login/_components/LoopyIconSection.tsx
  Loopy-fe/src/pages/User/Login/_components/SocialLoginSection.tsx
  Loopy-fe/src/pages/User/Login/index.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/PasswordHint.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/PasswordInput.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepEmail.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepVerify.tsx
  Loopy-fe/src/pages/User/Signin/index.tsx
  Loopy-fe/src/types/form.ts
Labels: fix, style

#22 Fix: recommend
  Loopy-fe/src/components/button/SelectableButton.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/StepCafeInfo.tsx
  Loopy-fe/src/pages/User/OnBoard/index.tsx
Labels: fix

#24 Feat: onBoarding page
  Loopy-fe/src/apis/kakao/address.ts
  Loopy-fe/src/assets/images/Destination.svg
  Loopy-fe/src/hooks/useSearchRegion.ts
  Loopy-fe/src/pages/User/OnBoard/_components/StepLocationPermission.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/StepSearchArea.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/search/CurrentLocationButton.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/search/SearchInputSection.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/search/SearchResultList.tsx
  Loopy-fe/src/pages/User/OnBoard/index.tsx
Labels: fix, feat

#27 Feat: search & location
  Loopy-fe/src/App.tsx
  Loopy-fe/src/assets/images/ArrowRight.svg
  Loopy-fe/src/assets/images/Bookmark-save.svg
  Loopy-fe/src/assets/images/Bookmark.svg
  Loopy-fe/src/assets/images/CafePic.svg
  Loopy-fe/src/assets/images/Location.svg
  Loopy-fe/src/assets/images/PinIcon.svg
  Loopy-fe/src/assets/images/RedImage.svg
  Loopy-fe/src/components/Input/SearchBar.tsx
  Loopy-fe/src/components/button/MapViewToggleButton.tsx
  Loopy-fe/src/components/card/CafeListCard.tsx
  Loopy-fe/src/components/card/CommonCard.tsx
  Loopy-fe/src/components/card/EventCard.tsx
  Loopy-fe/src/components/etc/KeywordTags.tsx
  Loopy-fe/src/components/etc/LocationLabel.tsx
  Loopy-fe/src/components/popup/BottomPopup.tsx
  Loopy-fe/src/pages/User/Location/_components/AddressCard.tsx
  Loopy-fe/src/pages/User/Location/index.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterBar.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterDropdownButton.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterIconButton.tsx
  Loopy-fe/src/pages/User/Map/index.tsx
  Loopy-fe/src/pages/User/Search/index.tsx
Labels: feat, chore, style

#29 Fix: font-login/signin
  Loopy-fe/src/components/Input/CommonInput.tsx
  Loopy-fe/src/components/button/CommonButton.tsx
  Loopy-fe/src/components/header/CommonHeader.tsx
  Loopy-fe/src/pages/Admin/Login/index.tsx
  Loopy-fe/src/pages/User/Login/_components/LoopyIconSection.tsx
  Loopy-fe/src/pages/User/Login/_components/SocialLoginSection.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/StepCafeInfo.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/search/CurrentLocationButton.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/search/SearchInputSection.tsx
  Loopy-fe/src/pages/User/Signin/_components/AgreementItem.tsx
  Loopy-fe/src/pages/User/Signin/_components/AgreementListView.tsx
  Loopy-fe/src/pages/User/Signin/_components/CheckCircle.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/PasswordInput.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepEmail.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepVerify.tsx
Labels: fix

#38 Fix: deploy_2
  Loopy-fe/src/pages/User/Login/_components/LoopyIconSection.tsx
Labels: fix

#43 Feat: challenge available cafe list
  Loopy-fe/src/App.tsx
  Loopy-fe/src/components/popup/CommonBottomPopup.tsx
  Loopy-fe/src/pages/User/Challenge/mock/mockData.ts
  Loopy-fe/src/pages/User/ChallengeDetail/ChallengeStoreListPage/index.tsx
  Loopy-fe/src/pages/User/ChallengeDetail/components/SmallButton.tsx
  Loopy-fe/src/pages/User/ChallengeDetail/index.tsx
Labels: feat, chore

#45 Feat: bookmark_page, alarm_page
  Loopy-fe/package.json
  Loopy-fe/pnpm-lock.yaml
  Loopy-fe/src/pages/User/Alarm/components/AlarmCard.tsx
  Loopy-fe/src/pages/User/Alarm/index.tsx
  Loopy-fe/src/pages/User/Alarm/mock/mockData.ts
  Loopy-fe/src/pages/User/BookMark/index.tsx
Labels: feat

#46 Fix: common-header
  Loopy-fe/src/assets/images/Back.svg
  Loopy-fe/src/components/header/CommonHeader.tsx
Labels: fix, style

#57 Feat: myStamp
  Loopy-fe/src/App.tsx
  Loopy-fe/src/assets/images/Info.svg
  Loopy-fe/src/assets/images/StampBackground.svg
  Loopy-fe/src/assets/images/Step10.svg
  Loopy-fe/src/assets/images/Vector.svg
  Loopy-fe/src/components/popup/CommonBottomPopup.tsx
  Loopy-fe/src/pages/User/Home/components/MyStamp.tsx
  Loopy-fe/src/pages/User/Home/mock/mockData.ts
  Loopy-fe/src/pages/User/MyStamp/components/StampPaper.tsx
  Loopy-fe/src/pages/User/MyStamp/index.tsx
Labels: feat, chore, style

#59 Feat: mypage-filterPage
  Loopy-fe/src/pages/User/My/Filter/index.tsx
  Loopy-fe/src/pages/User/My/index.tsx
Labels: feat, style

#60 Feat: DetailPage
  Loopy-fe/src/App.tsx
  Loopy-fe/src/assets/images/BellPlus.svg
  Loopy-fe/src/assets/images/CafePic2.svg
  Loopy-fe/src/assets/images/CafePic3.svg
  Loopy-fe/src/assets/images/Clock.svg
  Loopy-fe/src/assets/images/Close-White.svg
  Loopy-fe/src/assets/images/DeletePic.svg
  Loopy-fe/src/assets/images/Globe.svg
  Loopy-fe/src/assets/images/Phone.svg
  Loopy-fe/src/assets/images/PlusPic.svg
  Loopy-fe/src/assets/images/ReviewButton.svg
  Loopy-fe/src/assets/images/chevron-left-black.svg
  Loopy-fe/src/assets/images/chevron-left-white.svg
  Loopy-fe/src/assets/images/chevron-right-black.svg
  Loopy-fe/src/assets/images/chevron-right-white.svg
  Loopy-fe/src/components/button/SlideButton.tsx
  Loopy-fe/src/mock/cafeDetailMock.ts
  Loopy-fe/src/pages/User/Detail/_components/BusinessTimeSection.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoContent.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoPanel.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafePhotoModal.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeReviewContent.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeTagButton.tsx
  Loopy-fe/src/pages/User/Detail/_components/CouponCard.tsx
  Loopy-fe/src/pages/User/Detail/_components/MenuCard.tsx
  Loopy-fe/src/pages/User/Detail/_components/MyStampCard.tsx
  Loopy-fe/src/pages/User/Detail/_components/ReviewButton.tsx
  Loopy-fe/src/pages/User/Detail/_components/TopPhotoSection.tsx
  Loopy-fe/src/pages/User/Detail/index.tsx
  Loopy-fe/src/pages/User/Menu/index.tsx
  Loopy-fe/src/pages/User/Review/index.tsx
  Loopy-fe/src/types/cafeData.ts
Labels: feat, style

#62 Feat: mypage-cafenotice
  Loopy-fe/.eslintrc.js
  Loopy-fe/eslint.config.js
  Loopy-fe/src/assets/images/Toggle.svg
  Loopy-fe/src/pages/ErrorPage.tsx
  Loopy-fe/src/pages/User/My/CafeNotice/_components/MessageItem.tsx
  Loopy-fe/src/pages/User/My/CafeNotice/_components/MessageList.tsx
  Loopy-fe/src/pages/User/My/CafeNotice/index.tsx
  Loopy-fe/src/pages/User/My/CafeNotice/mock/messages.ts
  Loopy-fe/src/pages/User/My/index.tsx
Labels: feat, style

#64 Feat: mypage-coupon
  Loopy-fe/src/components/card/CommonCard.tsx
  Loopy-fe/src/pages/User/My/CouponBox/_components/CouponCard.tsx
  Loopy-fe/src/pages/User/My/CouponBox/_mock/coupons.ts
  Loopy-fe/src/pages/User/My/CouponBox/index.tsx
  Loopy-fe/src/pages/User/My/index.tsx
Labels: feat, style

#65 Feat: mypage-challengepage
  Loopy-fe/src/hooks/Funnel/useFunnel.tsx
  Loopy-fe/src/pages/User/My/Challenge/_components/ChallengeCard.tsx
  Loopy-fe/src/pages/User/My/Challenge/index.tsx
  Loopy-fe/src/pages/User/My/Challenge/mock/challenges.ts
  Loopy-fe/src/pages/User/My/Challenge/types/challenges.ts
  Loopy-fe/src/pages/User/My/index.tsx
Labels: refactor, feat

#66 Feat: mypage-review
  Loopy-fe/src/components/bottomBar/CommonBottomBar.tsx
  Loopy-fe/src/components/popup/CommonBottomPopup.tsx
  Loopy-fe/src/pages/User/My/Review/index.tsx
  Loopy-fe/src/pages/User/My/index.tsx
Labels: fix, feat

#71 Fix/map&detail
  Loopy-fe/package.json
  Loopy-fe/pnpm-lock.yaml
  Loopy-fe/src/components/input/SearchBar.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterBar.tsx
  Loopy-fe/src/pages/User/Map/index.tsx
  Loopy-fe/src/pages/User/Search/index.tsx
  Loopy-fe/tailwind.config.ts
Labels: fix, style

#75 Feat: qr_sample/popup
  Loopy-fe/src/assets/images/qr-sample.svg
  Loopy-fe/src/components/popup/CommonBottomPopup.tsx
  Loopy-fe/src/pages/User/My/_components/ProfileSection.tsx
  Loopy-fe/src/pages/User/My/_components/QuickAccessMenu.tsx
  Loopy-fe/tailwind.config.ts
Labels: fix, style

#76 Feat: stamphistory
  Loopy-fe/src/assets/images/MapPin.svg
  Loopy-fe/src/mock/stampHistoryDummy.ts
  Loopy-fe/src/pages/User/My/StampExchange/_components/StampBookItem.tsx
  Loopy-fe/src/pages/User/My/StampHistory/_components/StampHistoryItem.tsx
  Loopy-fe/src/pages/User/My/StampHistory/index.tsx
  Loopy-fe/src/pages/User/My/index.tsx
  Loopy-fe/src/types/stampHistory.ts
Labels: feat

#77 Fix: js-key
  Loopy-fe/src/apis/kakao/kakaoInstance.ts
Labels: fix

#78 Fix: bookmark
  Loopy-fe/src/pages/User/BookMark/index.tsx
Labels: fix

#79 Fix: image import
  Loopy-fe/src/components/card/EventCard.tsx
  Loopy-fe/src/components/input/SearchBar.tsx
  Loopy-fe/src/pages/User/Detail/_components/ReviewButton.tsx
  Loopy-fe/src/pages/User/Location/index.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterDropdownButton.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterIconButton.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterPopup.tsx
  Loopy-fe/src/pages/User/Map/index.tsx
Labels: fix, chore

#80 Fix: 파일 경로 수정
  Loopy-fe/src/components/card/EventCard.tsx
  Loopy-fe/src/pages/User/Map/_components/filter/FilterPopup.tsx
Labels: chore

#81 Style: mystamp
  Loopy-fe/src/pages/User/Alarm/mock/mockData.ts
  Loopy-fe/src/pages/User/Home/components/ExpireTag.tsx
  Loopy-fe/src/pages/User/Home/components/MyStamp.tsx
  Loopy-fe/src/pages/User/MyStamp/components/GetRemainingDays.ts
  Loopy-fe/src/pages/User/MyStamp/index.tsx
Labels: style

#83 Feat: onboard-locaton/skeleton
  Loopy-fe/index.html
  Loopy-fe/public/icon.png
  Loopy-fe/public/icon2.png
  Loopy-fe/public/icon3.png
  Loopy-fe/public/logo.svg
  Loopy-fe/src/App.tsx
  Loopy-fe/src/apis/kakao/kakaoInstance.ts
  Loopy-fe/src/assets/logo.svg
  Loopy-fe/src/contexts/OnboardingContext.tsx
  Loopy-fe/src/hooks/useSearchRegion.ts
  Loopy-fe/src/main.tsx
  Loopy-fe/src/pages/User/OnBoard/OnboardingWrapper.tsx
  Loopy-fe/src/pages/User/OnBoard/Skeleton/SearchResultSkeleton.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/StepCafeInfo.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/StepSearchArea.tsx
  Loopy-fe/src/pages/User/OnBoard/index.tsx
  Loopy-fe/src/vite-env.d.ts
  Loopy-fe/vite.config.ts
Labels: refactor, feat, setting

#94 Fix: message-alarm
  Loopy-fe/src/pages/User/My/CafeNotice/_components/MessageItem.tsx
  Loopy-fe/src/pages/User/My/CafeNotice/mock/messages.ts
Labels: fix, style

#95 Fix: MapPage
  Loopy-fe/src/assets/images/NoStampActiveMarker.svg
  Loopy-fe/src/assets/images/NoStampDefaultMarker.svg
  Loopy-fe/src/assets/images/StampActiveMarker.svg
  Loopy-fe/src/assets/images/StampDefaultMarker.svg
  Loopy-fe/src/components/card/MapCafeDetailCard.tsx
  Loopy-fe/src/components/etc/LocationLabel.tsx
  Loopy-fe/src/pages/User/Map/index.tsx
Labels: fix, chore

#96 Feat: home skeleton
  Loopy-fe/src/components/popup/CommonBottomPopup.tsx
  Loopy-fe/src/pages/User/Alarm/Skeleton/AlarmSkeleton.tsx
  Loopy-fe/src/pages/User/Alarm/components/AlarmCard.tsx
  Loopy-fe/src/pages/User/Alarm/index.tsx
  Loopy-fe/src/pages/User/Alarm/mock/mockData.ts
  Loopy-fe/src/pages/User/BookMark/Skeleton/BookMarkSkeleton.tsx
  Loopy-fe/src/pages/User/BookMark/index.tsx
  Loopy-fe/src/pages/User/Challenge/Skeleton/ChallengeCardSkeleton.tsx
  Loopy-fe/src/pages/User/Challenge/Skeleton/ChallengeListSkeleton.tsx
  Loopy-fe/src/pages/User/Challenge/components/ChallengeCard.tsx
  Loopy-fe/src/pages/User/Challenge/index.tsx
  Loopy-fe/src/pages/User/Challenge/mock/mockData.ts
  Loopy-fe/src/pages/User/ChallengeDetail/ChallengeStoreListPage/index.tsx
  Loopy-fe/src/pages/User/ChallengeDetail/Skeleton/ChallengeDetailSkeleton.tsx
  Loopy-fe/src/pages/User/ChallengeDetail/Skeleton/ChallengeStorListSkeleton.tsx
  Loopy-fe/src/pages/User/ChallengeDetail/index.tsx
  Loopy-fe/src/pages/User/Home/Skeleton/HomeSkeleton.tsx
  Loopy-fe/src/pages/User/Home/Skeleton/ProfileCardSkeleton.tsx
  Loopy-fe/src/pages/User/Home/components/ChallengeCarousel.tsx
  Loopy-fe/src/pages/User/Home/components/MyStamp.tsx
  Loopy-fe/src/pages/User/Home/components/ProfileCard.tsx
  Loopy-fe/src/pages/User/Home/index.tsx
  Loopy-fe/src/pages/User/MyStamp/Skeleton/MyStampSkeleton.tsx
  Loopy-fe/src/pages/User/MyStamp/index.tsx
Labels: feat, chore, style

#99 Feat: token-storage
  Loopy-fe/package.json
  Loopy-fe/pnpm-lock.yaml
  Loopy-fe/src/App.tsx
  Loopy-fe/src/pages/User/OnBoard/index.tsx
  Loopy-fe/src/store/useAuthStore.ts
  Loopy-fe/src/utils/authCheck.ts
  Loopy-fe/src/utils/crypto.ts
  Loopy-fe/src/utils/storage.ts
Labels: feat

#102 Api: login-signup [mocks connect]
  Loopy-fe/src/apis/axios.ts
  Loopy-fe/src/apis/login/api.ts
  Loopy-fe/src/apis/login/type.ts
  Loopy-fe/src/apis/signin/api.ts
  Loopy-fe/src/apis/signin/type.ts
  Loopy-fe/src/apis/types/ApiResponse.ts
  Loopy-fe/src/components/button/SelectableButton.tsx
  Loopy-fe/src/components/input/CommonInput.tsx
  Loopy-fe/src/hooks/action/useHandleLogin.ts
  Loopy-fe/src/hooks/query/login/useLogin.ts
  Loopy-fe/src/hooks/query/signin/useSignup.ts
  Loopy-fe/src/pages/User/Login/index.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepVerify.tsx
  Loopy-fe/src/pages/User/Signin/_components/verify/PhoneInput.tsx
  Loopy-fe/src/pages/User/Signin/_components/verify/SignupButton.tsx
  Loopy-fe/src/pages/User/Signin/_components/verify/VeryfyCodeInput.tsx
  Loopy-fe/src/utils/mapper.ts
Labels: api, feat

#105 Fix: mypage
  Loopy-fe/package.json
  Loopy-fe/pnpm-lock.yaml
  Loopy-fe/src/App.tsx
  Loopy-fe/src/contexts/MyFunnelProvider.tsx
  Loopy-fe/src/hooks/Funnel/useFunnel.tsx
  Loopy-fe/src/layouts/MyPageFunnelLayout.tsx
  Loopy-fe/src/layouts/OnboardingLayout.tsx
  Loopy-fe/src/pages/User/My/CouponBox/index.tsx
  Loopy-fe/src/pages/User/My/Setting/_components/EditProfile.tsx
  Loopy-fe/src/pages/User/My/Setting/_components/ManageAccount.tsx
  Loopy-fe/src/pages/User/My/Setting/index.tsx
  Loopy-fe/src/pages/User/My/StampExchange/_components/StampBookItem.tsx
  Loopy-fe/src/pages/User/My/StampHistory/index.tsx
  Loopy-fe/src/pages/User/My/_components/ActivityList.tsx
  Loopy-fe/src/pages/User/My/_components/CafeNotification.tsx
  Loopy-fe/src/pages/User/My/_components/MainMyPage.tsx
  Loopy-fe/src/pages/User/My/_components/ProfileSection.tsx
  Loopy-fe/src/pages/User/My/_components/QuickAccessMenu.tsx
  Loopy-fe/src/pages/User/My/index.tsx
  Loopy-fe/src/pages/User/OnBoard/OnboardingWrapper.tsx
  Loopy-fe/src/types/mySteps.ts
Labels: fix, feat

#106 Api: onboard [mock]
  Loopy-fe/src/apis/onboard/api.ts
  Loopy-fe/src/apis/onboard/type.ts
  Loopy-fe/src/hooks/query/onboard/usePreferredArea.ts
  Loopy-fe/src/pages/User/OnBoard/_components/StepCafeInfo.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/StepSearchArea.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/TagSection.tsx
Labels: api, feat

#109 feat/searchpage-skeleton
  Loopy-fe/src/components/etc/KeywordTags.tsx
  Loopy-fe/src/pages/User/Search/Skeleton/CafeListCardSkeleton.tsx
  Loopy-fe/src/pages/User/Search/Skeleton/EventCardSkeleton.tsx
  Loopy-fe/src/pages/User/Search/index.tsx
Labels: feat, style

#114 Fix: my-review
  Loopy-fe/src/pages/User/My/MyReview/Skeleton/EditReviewSkeleton.tsx
  Loopy-fe/src/pages/User/My/MyReview/Skeleton/MyReviewSkeleton.tsx
  Loopy-fe/src/pages/User/My/MyReview/_components/EditReviewPage.tsx
  Loopy-fe/src/pages/User/My/MyReview/_components/ReviewBottomButton.tsx
  Loopy-fe/src/pages/User/My/MyReview/_components/ReviewImageBox.tsx
  Loopy-fe/src/pages/User/My/MyReview/_components/ReviewImageSlider.tsx
  Loopy-fe/src/pages/User/My/MyReview/_components/ReviewItem.tsx
  Loopy-fe/src/pages/User/My/MyReview/_components/ReviewTextArea.tsx
  Loopy-fe/src/pages/User/My/MyReview/index.tsx
  Loopy-fe/src/pages/User/My/Review/index.tsx
  Loopy-fe/src/pages/User/My/index.tsx
Labels: fix, feat

#116 Fix: mypage-stampbook
  Loopy-fe/src/pages/User/My/StampExchange/_components/StampBookItem.tsx
  Loopy-fe/src/pages/User/My/StampExchange/_components/StampDetailPage.tsx
  Loopy-fe/src/pages/User/My/StampExchange/index.tsx
  Loopy-fe/src/pages/User/MyStamp/components/StampPaper.tsx
Labels: fix, feat

#123 Api: challenge
  Loopy-fe/src/apis/challenge/challengeDetail/api.ts
  Loopy-fe/src/apis/challenge/challengeDetail/mocks.ts
  Loopy-fe/src/apis/challenge/challengeDetail/type.ts
  Loopy-fe/src/apis/challenge/challengeList/api.ts
  Loopy-fe/src/apis/challenge/challengeList/mocks.ts
  Loopy-fe/src/apis/challenge/challengeList/type.ts
  Loopy-fe/src/hooks/query/challenge/useChallengeDetail.ts
  Loopy-fe/src/hooks/query/challenge/useChallengeList.ts
  Loopy-fe/src/pages/User/Challenge/components/AllChallengeList.tsx
  Loopy-fe/src/pages/User/Challenge/components/ChallengeCard.tsx
  Loopy-fe/src/pages/User/Challenge/components/ParticipatingChallengeList.tsx
  Loopy-fe/src/pages/User/Challenge/index.tsx
  Loopy-fe/src/pages/User/ChallengeDetail/index.tsx
  Loopy-fe/src/pages/User/Home/components/ChallangeCard.tsx
  Loopy-fe/src/pages/User/Home/components/ChallengeCarousel.tsx
  Loopy-fe/src/pages/User/Home/components/NoChallangeCard.tsx
  Loopy-fe/src/pages/User/Home/index.tsx
  Loopy-fe/src/pages/User/Home/mock/mockData.ts
Labels: api, chore, style

#126 Feat: admin/CommonSideBar
  Loopy-fe/src/App.tsx
  Loopy-fe/src/assets/images/AdminChallenge.svg
  Loopy-fe/src/assets/images/AdminChallengePurple.svg
  Loopy-fe/src/assets/images/AdminCoupon.svg
  Loopy-fe/src/assets/images/AdminCouponPurple.svg
  Loopy-fe/src/assets/images/AdminHome.svg
  Loopy-fe/src/assets/images/AdminHomePurple.svg
  Loopy-fe/src/assets/images/AdminLogout.svg
  Loopy-fe/src/assets/images/AdminSetting.svg
  Loopy-fe/src/assets/images/AdminStamp.svg
  Loopy-fe/src/assets/images/AdminStampPurple.svg
  Loopy-fe/src/components/admin/sideBar/CommonSideBar.tsx
  Loopy-fe/src/pages/Admin/Challenge/index.tsx
  Loopy-fe/src/pages/Admin/Coupon/index.tsx
  Loopy-fe/src/pages/Admin/Home/index.tsx
  Loopy-fe/src/pages/Admin/Stamp/index.tsx
Labels: feat

#128 Api: agreement
  Loopy-fe/src/apis/agree/api.ts
  Loopy-fe/src/apis/agree/type.ts
  Loopy-fe/src/apis/signin/api.ts
  Loopy-fe/src/apis/signin/type.ts
  Loopy-fe/src/hooks/mutation/onboard/usePatchAgreement.ts
  Loopy-fe/src/hooks/mutation/onboard/usePreferredArea.ts
  Loopy-fe/src/pages/Admin/Signin/_components/AdminSignupButton.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminStepPhoneVerify.tsx
  Loopy-fe/src/pages/Admin/Signin/index.tsx
  Loopy-fe/src/pages/User/Login/_components/SocialLoginSection.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/StepCafeInfo.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/StepSearchArea.tsx
  Loopy-fe/src/pages/User/Signin/_components/AgreementListView.tsx
  Loopy-fe/src/pages/User/Signin/index.tsx
  Loopy-fe/src/types/form.ts
  Loopy-fe/src/utils/mapper.ts
Labels: fix, api, feat

#130 Api: my-settingpage
  Loopy-fe/src/apis/auth/active/api.ts
  Loopy-fe/src/apis/auth/active/type.ts
  Loopy-fe/src/apis/auth/login/api.ts
  Loopy-fe/src/apis/auth/login/type.ts
  Loopy-fe/src/apis/auth/logout/api.ts
  Loopy-fe/src/apis/auth/logout/type.ts
  Loopy-fe/src/apis/auth/signin/api.ts
  Loopy-fe/src/apis/auth/signin/type.ts
  Loopy-fe/src/apis/userInfo/api.ts
  Loopy-fe/src/apis/userInfo/type.ts
  Loopy-fe/src/hooks/action/useHandleLogin.ts
  Loopy-fe/src/hooks/mutation/active/useActiveStatus.ts
  Loopy-fe/src/hooks/mutation/login/useLogin.ts
  Loopy-fe/src/hooks/mutation/logout/useLogout.ts
  Loopy-fe/src/hooks/mutation/signin/useSignup.ts
  Loopy-fe/src/hooks/mutation/userInfo/usePatchNickname.ts
  Loopy-fe/src/hooks/query/userInfo/useMyInfo.ts
  Loopy-fe/src/pages/Admin/Signin/_components/AdminSignupButton.tsx
  Loopy-fe/src/pages/User/My/Setting/_components/DefaultAccountView.tsx
  Loopy-fe/src/pages/User/My/Setting/_components/EditProfile.tsx
  Loopy-fe/src/pages/User/My/Setting/_components/ManageAccount.tsx
  Loopy-fe/src/pages/User/My/Setting/_components/WithdrawAccountView.tsx
  Loopy-fe/src/pages/User/Signin/_components/verify/SignupButton.tsx
Labels: fix, api, feat

#134 Api: kakao-login
  Loopy-fe/src/apis/agree/api.ts
  Loopy-fe/src/apis/userInfo/qr/api.ts
  Loopy-fe/src/apis/userInfo/qr/type.ts
  Loopy-fe/src/hooks/query/userInfo/qr/useUserQRCode.ts
  Loopy-fe/src/pages/User/Login/_components/SocialLoginSection.tsx
  Loopy-fe/src/pages/User/My/_components/ProfileSection.tsx
  Loopy-fe/src/pages/User/Signin/_components/verify/SignupButton.tsx
  Loopy-fe/src/pages/auth/LoginSuccess.tsx
  Loopy-fe/src/utils/storage.ts
Labels: fix, api, feat

#137 Fix: api home
  Loopy-fe/src/apis/alarm/api.ts
  Loopy-fe/src/apis/stampBook/stampBookDetail/type.ts
Labels: fix

#141 Fix: sms-verify
  Loopy-fe/src/hooks/usePhoneVerification.ts
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepVerify.tsx
Labels: fix, api

#143 Api: kakao/fcm-patch
  Loopy-fe/src/pages/Admin/Signin/_components/AdminSignupButton.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminStepPhoneVerify.tsx
  Loopy-fe/src/pages/Admin/Signin/index.tsx
  Loopy-fe/src/pages/auth/LoginSuccess.tsx
Labels: api, feat

#145 Fix: kakao
  Loopy-fe/src/pages/auth/LoginSuccess.tsx
Labels: fix

#147 Fix: pwa-image/ios-zoom
  Loopy-fe/index.html
  Loopy-fe/vite.config.ts
Labels: fix
