Repository Organization-LOOPy/LOOPy-FE, pull requests merged in 2025-08, with the labels that each got.

#148 Api: 리뷰 작성 api(연결X) 및 Fix: location page
  Loopy-fe/src/apis/review/get/api.ts
  Loopy-fe/src/apis/review/get/type.ts
  Loopy-fe/src/apis/review/post/api.ts
  Loopy-fe/src/apis/review/post/type.ts
  Loopy-fe/src/assets/images/NoStampActiveMarker.svg
  Loopy-fe/src/assets/images/NoStampDefaultMarker.svg
  Loopy-fe/src/assets/images/StampActiveMarker.svg
  Loopy-fe/src/assets/images/StampDefaultMarker.svg
  Loopy-fe/src/hooks/mutation/detail/useIssueCoupon.ts
  Loopy-fe/src/hooks/mutation/detail/usePostReview.ts
  Loopy-fe/src/mock/cafeReviewMock.ts
  Loopy-fe/src/mock/reviewPostMock.ts
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoContent.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoPanel.tsx
  Loopy-fe/src/pages/User/Detail/_components/CouponCard.tsx
  Loopy-fe/src/pages/User/Detail/_components/ReviewButton.tsx
  Loopy-fe/src/pages/User/Location/index.tsx
  Loopy-fe/src/pages/User/Map/index.tsx
  Loopy-fe/src/pages/User/Review/index.tsx
  Loopy-fe/src/utils/formatReview.ts
  Loopy-fe/src/utils/handleIssueCoupon.ts
Labels: fix, api

#155 Api: ReviewContent
  Loopy-fe/src/apis/cafeStamp/api.ts
  Loopy-fe/src/apis/cafeStamp/type.ts
  Loopy-fe/src/hooks/mutation/detail/useMyStampQuery.ts
  Loopy-fe/src/pages/User/Detail/_components/CafeReviewContent.tsx
  Loopy-fe/src/pages/User/Detail/_components/TopPhotoSection.tsx
  Loopy-fe/src/pages/User/Detail/index.tsx
  Loopy-fe/src/pages/User/Menu/index.tsx
Labels: fix, api, chore

#159 Feat: admin/home
  Loopy-fe/src/assets/images/AdminBell.svg
  Loopy-fe/src/assets/images/AdminHomeCharacter.svg
  Loopy-fe/src/assets/images/AdminMessage.svg
  Loopy-fe/src/assets/images/AdminQRIcon.svg
  Loopy-fe/src/assets/images/AdminSettingPurple.svg
  Loopy-fe/src/assets/images/AdminStampIcon.svg
  Loopy-fe/src/assets/images/LoopyLogo.svg
  Loopy-fe/src/assets/images/QuestionMark.svg
  Loopy-fe/src/components/admin/sideBar/CommonSideBar.tsx
  Loopy-fe/src/components/admin/topBar/CommonTopBar.tsx
  Loopy-fe/src/layouts/AdminLayout.tsx
  Loopy-fe/src/pages/Admin/Home/components/AnalysisCard.tsx
  Loopy-fe/src/pages/Admin/Home/components/ChallengeCard.tsx
  Loopy-fe/src/pages/Admin/Home/components/CouponCard.tsx
  Loopy-fe/src/pages/Admin/Home/components/HomeButton.tsx
  Loopy-fe/src/pages/Admin/Home/components/HomeQRButton.tsx
  Loopy-fe/src/pages/Admin/Home/components/HomeStampButton.tsx
  Loopy-fe/src/pages/Admin/Home/components/StampOverview.tsx
  Loopy-fe/src/pages/Admin/Home/index.tsx
Labels: feat, chore

#160 Feat: admin-home
  Loopy-fe/src/apis/my/convertedStamp/api.ts
  Loopy-fe/src/apis/my/convertedStamp/mock.ts
  Loopy-fe/src/apis/my/convertedStamp/type.ts
  Loopy-fe/src/components/admin/topBar/CommonTopBar.tsx
  Loopy-fe/src/hooks/query/my/useConvertedStampBook.ts
  Loopy-fe/src/index.css
  Loopy-fe/src/layouts/AdminLayout.tsx
  Loopy-fe/src/pages/Admin/Home/index.tsx
  Loopy-fe/src/pages/User/My/StampExchange/index.tsx
  Loopy-fe/src/pages/User/My/StampHistory/_components/StampHistoryItem.tsx
  Loopy-fe/src/pages/User/My/StampHistory/index.tsx
  Loopy-fe/src/types/stampHistory.ts
Labels: fix, api, style

#165 Fix: commonTabBar
  Loopy-fe/src/components/admin/topBar/CommonTopBar.tsx
Labels: fix, style

#167 Style: admin/coupon
  Loopy-fe/src/assets/images/Toggle.svg
  Loopy-fe/src/pages/Admin/Coupon/_components/AddCouponButton.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/CouponList.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/FilterToggleButton.tsx
  Loopy-fe/src/pages/Admin/Coupon/index.tsx
Labels: feat, style

#171 Style: admin/coupon-create
  Loopy-fe/package.json
  Loopy-fe/pnpm-lock.yaml
  Loopy-fe/src/apis/admin/coupon/mocks.ts
  Loopy-fe/src/assets/images/CalendarIcon.svg
  Loopy-fe/src/components/admin/button/CommonAdminButton.tsx
  Loopy-fe/src/hooks/Funnel/useFunnel.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/AddCouponButton.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/AdminCouponListPage.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/AdminCreateCouponPage.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/CouponConditionSection.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/CouponLimitSection.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/CouponTypeSection.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/DateRangePicker.tsx
  Loopy-fe/src/pages/Admin/Coupon/index.tsx
Labels: fix, style

#174 Fix: imageToggle
  Loopy-fe/src/pages/User/My/MyReview/_components/ReviewImageSlider.tsx
Labels: fix

#175 Fix: admin/signin
  Loopy-fe/src/pages/Admin/Signin/_components/AdminPasswordInput.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminPhoneInput.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminSignupButton.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminSignupSuccess.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminSinginPage.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminStepPhoneVerify.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminVerifyCodeInput.tsx
  Loopy-fe/src/pages/Admin/Signin/index.tsx
Labels: fix, style

#176 Style: admin/login signin
  Loopy-fe/src/App.tsx
  Loopy-fe/src/hooks/action/useAdminHandleLogin.tsx
  Loopy-fe/src/pages/Admin/Login/_components/AdminSocialLogin.tsx
  Loopy-fe/src/pages/Admin/Login/index.tsx
Labels: fix, api

#181 Feat: admin/logout
  Loopy-fe/src/components/admin/modal/CommonTwoButtonModal.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/AdminManageAccount.tsx
Labels: api, feat

#189 Feat: admin/challengeDetail
  Loopy-fe/src/assets/images/Graph.svg
  Loopy-fe/src/pages/Admin/Challenge/_components/AdminChallengeDetail.tsx
  Loopy-fe/src/pages/Admin/Challenge/_components/ChallengeInfoCard.tsx
  Loopy-fe/src/pages/Admin/Challenge/_constants/ChallengeConfig.ts
Labels: feat

#191 Style/admin/setting
  Loopy-fe/src/assets/images/CameraPlus.svg
  Loopy-fe/src/components/admin/button/CommonAdminButton.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/AdminCreateCouponPage.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/BasicInfoTab.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/basic/DescriptionArea.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/basic/PhoneInput.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/basic/PhotoUploader.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/basic/SNSInput.tsx
Labels: feat, style

#201 Api: admin coupon
  Loopy-fe/src/App.tsx
  Loopy-fe/src/apis/admin/coupon/api.ts
  Loopy-fe/src/apis/admin/coupon/create/api.ts
  Loopy-fe/src/apis/admin/coupon/type.ts
  Loopy-fe/src/assets/images/AllReset.svg
  Loopy-fe/src/components/admin/modal/CommonTwoButtonModal.tsx
  Loopy-fe/src/components/admin/sideBar/CommonSideBar.tsx
  Loopy-fe/src/hooks/query/admin/coupon/useCreateOwnerCoupon.ts
  Loopy-fe/src/hooks/query/admin/coupon/useOwnerCoupon.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/AdminCouponListPage.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/AdminCreateCouponPage.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/FilterToggleButton.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/TypeFilterModal.tsx
  Loopy-fe/src/pages/Admin/Coupon/index.tsx
  Loopy-fe/src/utils/couponType.ts
Labels: fix, api, feat

#199 Feat: 매장등록 페이지
  Loopy-fe/src/App.tsx
  Loopy-fe/src/assets/images/AddIconPurple.svg
  Loopy-fe/src/assets/images/AddStampIcon.svg
  Loopy-fe/src/assets/images/ArrowDownPurple.svg
  Loopy-fe/src/assets/images/ArrowUpPurple.svg
  Loopy-fe/src/assets/images/CheckWhite.svg
  Loopy-fe/src/assets/images/ClosePurple.svg
  Loopy-fe/src/assets/images/DeleteMenu.svg
  Loopy-fe/src/assets/images/DeletePic.svg
  Loopy-fe/src/assets/images/Stamp1.svg
  Loopy-fe/src/assets/images/Stamp2.svg
  Loopy-fe/src/components/button/TagButton.tsx
  Loopy-fe/src/layouts/AdminRegisterContetntLayout.tsx
  Loopy-fe/src/pages/Admin/Register/_components/AddButton.tsx
  Loopy-fe/src/pages/Admin/Register/_components/AgreementItemPlain.tsx
  Loopy-fe/src/pages/Admin/Register/_components/BasicInput.tsx
  Loopy-fe/src/pages/Admin/Register/_components/BigAddButton.tsx
  Loopy-fe/src/pages/Admin/Register/_components/KeywordSelector.tsx
  Loopy-fe/src/pages/Admin/Register/_components/MenuDropdown.tsx
  Loopy-fe/src/pages/Admin/Register/_components/ModalLocationSelector.tsx
  Loopy-fe/src/pages/Admin/Register/_components/ModalMenuForm.tsx
  Loopy-fe/src/pages/Admin/Register/_components/NumberInput.tsx
  Loopy-fe/src/pages/Admin/Register/_components/RemovableKeywordTags.tsx
  Loopy-fe/src/pages/Admin/Register/_components/SelectableDayButton.tsx
  Loopy-fe/src/pages/Admin/Register/_components/SelectableItem.tsx
  Loopy-fe/src/pages/Admin/Register/_components/StampThumbnailSelector.tsx
  Loopy-fe/src/pages/Admin/Register/_components/StepProgress.tsx
  Loopy-fe/src/pages/Admin/Register/_components/TimeInput.tsx
  Loopy-fe/src/pages/Admin/Register/_components/TimeSection.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step1DocumentGuide.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step2BasicInfo.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step3BusinessInfo.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step4Menu.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step5Stamp.tsx
  Loopy-fe/src/pages/Admin/Register/index.tsx
  Loopy-fe/src/pages/User/Detail/_components/MenuCard.tsx
Labels: feat, style

#206 Api: admin/setting-basicInfo
  Loopy-fe/src/apis/admin/photo/api.ts
  Loopy-fe/src/apis/admin/photo/delete/api.ts
  Loopy-fe/src/apis/admin/photo/delete/type.ts
  Loopy-fe/src/apis/admin/photo/type.ts
  Loopy-fe/src/apis/admin/setting/basic/patch/api.ts
  Loopy-fe/src/apis/admin/setting/basic/patch/type.ts
  Loopy-fe/src/apis/admin/setting/basic/post/api.ts
  Loopy-fe/src/apis/admin/setting/basic/type.ts
  Loopy-fe/src/components/admin/sideBar/CommonSideBar.tsx
  Loopy-fe/src/contexts/AdminContext.tsx
  Loopy-fe/src/hooks/mutation/admin/basic/usePatchOwnerCafeBasicInfo.ts
  Loopy-fe/src/hooks/mutation/admin/basic/usePostOwnerCafeBasicInfo.ts
  Loopy-fe/src/hooks/mutation/admin/photo/useDeleteOwnerPhoto.ts
  Loopy-fe/src/hooks/mutation/admin/photo/useOwnerPhoto.ts
  Loopy-fe/src/hooks/useBasicInfoForm.ts
  Loopy-fe/src/hooks/useBasicInfoForm/index.ts
  Loopy-fe/src/hooks/useBasicInfoForm/useDraft.ts
  Loopy-fe/src/hooks/useBasicInfoForm/useServerHydration.ts
  Loopy-fe/src/hooks/useBasicInfoForm/useValidation.ts
  Loopy-fe/src/layouts/AdminLayout.tsx
  Loopy-fe/src/pages/Admin/Coupon/index.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/AdminManageAccount.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/basic/BasicInfoFormView.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/basic/PhotoUploader.tsx
  Loopy-fe/src/types/adminSteps.ts
  Loopy-fe/src/types/basicInfo.ts
Labels: fix, feat

#210 Fix: myInfo
  Loopy-fe/src/assets/images/LevelOne.svg
  Loopy-fe/src/assets/images/LevelThree.svg
  Loopy-fe/src/assets/images/LevelTwo.svg
  Loopy-fe/src/pages/User/My/_components/CafeNotification.tsx
  Loopy-fe/src/pages/User/My/_components/ProfileSection.tsx
  Loopy-fe/src/pages/User/My/_components/QuickAccessMenu.tsx
Labels: fix, api

#213 Api/admin/setting
  Loopy-fe/src/contexts/AdminSettingProvider.tsx
  Loopy-fe/src/hooks/action/useAdminHandleLogin.tsx
  Loopy-fe/src/pages/Admin/Register/index.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/MenuRegisterTab.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/basic/AddressSearchField.tsx
  Loopy-fe/src/types/adminSteps.ts
Labels: fix, feat

#215 Api: admin/withdraw
  Loopy-fe/src/apis/auth/ownerDelete/api.ts
  Loopy-fe/src/apis/auth/ownerDelete/type.ts
  Loopy-fe/src/hooks/mutation/admin/withdraw/useOwnerWithdraw.ts
  Loopy-fe/src/pages/Admin/Setting/_components/AdminWithdrawView.tsx
Labels: api, chore

#220 Fix: home/stampbook 충돌 해결
  Loopy-fe/src/apis/myStamp/api.ts
  Loopy-fe/src/apis/stampBook/api.ts
  Loopy-fe/src/hooks/query/stampBook/useStampBook.ts
  Loopy-fe/src/pages/User/Home/components/MyStamp.tsx
Labels: fix

#223 Fix: detail 페이지 수정
  Loopy-fe/src/apis/cafeDetail/type.ts
  Loopy-fe/src/pages/User/Detail/_components/BusinessTimeSection.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoContent.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoPanel.tsx
  Loopy-fe/src/pages/User/Detail/index.tsx
  Loopy-fe/src/utils/parseBusinessHours.ts
Labels: fix, api

#227 Api: admin challenge
  Loopy-fe/src/apis/admin/challenge/available/api.ts
  Loopy-fe/src/apis/admin/challenge/available/type.ts
  Loopy-fe/src/apis/admin/challenge/detail/api.ts
  Loopy-fe/src/apis/admin/challenge/detail/type.ts
  Loopy-fe/src/apis/admin/challenge/in-progress/api.ts
  Loopy-fe/src/apis/admin/challenge/in-progress/type.ts
  Loopy-fe/src/apis/admin/challenge/join/api.ts
  Loopy-fe/src/apis/admin/challenge/join/type.ts
  Loopy-fe/src/apis/admin/challenge/past/api.ts
  Loopy-fe/src/apis/admin/challenge/past/type.ts
  Loopy-fe/src/apis/admin/challenge/statistics/api.ts
  Loopy-fe/src/apis/admin/challenge/statistics/type.ts
  Loopy-fe/src/hooks/query/admin/challenge/useAvailableChallenges.ts
  Loopy-fe/src/hooks/query/admin/challenge/useChallengeDetail.ts
  Loopy-fe/src/hooks/query/admin/challenge/useChallengeStatistics.ts
  Loopy-fe/src/hooks/query/admin/challenge/useInProgressChallenges.ts
  Loopy-fe/src/hooks/query/admin/challenge/useJoinChallenge.ts
  Loopy-fe/src/hooks/query/admin/challenge/usePastChallenges.ts
Labels: api

#228 fix/pwa
  Loopy-fe/src/mock/cafeDetailMock.ts
  Loopy-fe/vite.config.ts
Labels: fix

#240 chore: 매장등록 운영시간 수정
  Loopy-fe/src/pages/Admin/Register/_components/AllDayTimeInput.tsx
  Loopy-fe/src/pages/Admin/Register/_components/ByDayTimeInput.tsx
  Loopy-fe/src/pages/Admin/Register/_components/SelectableDayButton.tsx
  Loopy-fe/src/pages/Admin/Register/_components/TimeInput.tsx
  Loopy-fe/src/pages/Admin/Register/_components/TimeSection.tsx
  Loopy-fe/src/pages/Admin/Register/_components/WeekdayWeekendTimeInput.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step2BasicInfo.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step3BusinessInfo.tsx
  Loopy-fe/src/utils/timeValidation.ts
Labels: chore, style

#253 Fix: myNotice
  Loopy-fe/src/apis/my/alarm/api.ts
  Loopy-fe/src/apis/my/alarm/mock.ts
  Loopy-fe/src/apis/my/alarm/type.ts
  Loopy-fe/src/hooks/query/my/useMyNotifications.ts
  Loopy-fe/src/pages/User/My/CafeNotice/_components/MessageItem.tsx
  Loopy-fe/src/pages/User/My/CafeNotice/_components/MessageList.tsx
  Loopy-fe/src/pages/User/My/CafeNotice/index.tsx
Labels: fix, api

#259 fix: build
  Loopy-fe/src/main.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminStepPhoneVerify.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepVerify.tsx
Labels: fix

#263 Api: feat/qr-interaction
  Loopy-fe/src/apis/my/challenge/api.ts
  Loopy-fe/src/apis/my/challenge/type.ts
  Loopy-fe/src/apis/my/coupon/patch/api.ts
  Loopy-fe/src/apis/my/coupon/patch/type.ts
  Loopy-fe/src/hooks/mutation/my/challenge/useChallengeMutation.ts
  Loopy-fe/src/hooks/mutation/my/coupon/useMyCoupon.ts
  Loopy-fe/src/pages/User/My/_components/MainMyPage.tsx
  Loopy-fe/src/pages/User/My/_components/ProfileHeader.tsx
  Loopy-fe/src/pages/User/My/_components/ProfileSection.tsx
  Loopy-fe/src/pages/User/My/_components/ProfileStats.tsx
  Loopy-fe/src/pages/User/My/_components/QrPopup.tsx
  Loopy-fe/src/pages/User/My/handlers/handleCouponScan.ts
  Loopy-fe/src/pages/User/My/handlers/useChallengeHandlers.ts
  Loopy-fe/src/pages/User/My/index.tsx
Labels: api, feat

#267 deploy/fix/route-onboard
  Loopy-fe/src/pages/auth/VerifyPage.tsx
Labels: fix

#268 Fix: QA 사항 수정
  Loopy-fe/src/apis/bookmark/api.ts
  Loopy-fe/src/apis/listSearch/type.ts
  Loopy-fe/src/apis/mapCafeDetail/api.ts
  Loopy-fe/src/apis/mapSearch/type.ts
  Loopy-fe/src/apis/notification/api.ts
  Loopy-fe/src/apis/review/post/api.ts
  Loopy-fe/src/assets/images/AlertCircle.svg
  Loopy-fe/src/components/button/BookmarkButton.tsx
  Loopy-fe/src/components/card/CafeListCard.tsx
  Loopy-fe/src/components/card/MapCafeDetailCard.tsx
  Loopy-fe/src/features/filter/filterMapping.ts
  Loopy-fe/src/hooks/mutation/cafe/useToggleBookmark.ts
  Loopy-fe/src/hooks/mutation/detail/useCreateBookmark.ts
  Loopy-fe/src/hooks/mutation/detail/useNotification.ts
  Loopy-fe/src/hooks/query/bookmark/useBookmarkdeCafeQuery.ts
  Loopy-fe/src/hooks/query/cafe/useCafeList.ts
  Loopy-fe/src/pages/Admin/Stamp/_components/StampStatsBar.tsx
  Loopy-fe/src/pages/User/Detail/_components/AlarmSubscribeButton.tsx
  Loopy-fe/src/pages/User/Detail/_components/BaseModal.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoContent.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoPanel.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafePhotoModal.tsx
  Loopy-fe/src/pages/User/Detail/_components/CouponCard.tsx
  Loopy-fe/src/pages/User/Detail/_components/CouponModal.tsx
  Loopy-fe/src/pages/User/Detail/_components/MyStampCard.tsx
  Loopy-fe/src/pages/User/Detail/_components/ReviewButton.tsx
  Loopy-fe/src/pages/User/Detail/_components/ReviewRestrictionModal.tsx
  Loopy-fe/src/pages/User/Detail/index.tsx
  Loopy-fe/src/pages/User/Map/index.tsx
  Loopy-fe/src/pages/User/Review/index.tsx
  Loopy-fe/src/pages/User/Search/index.tsx
Labels: fix, api, feat, chore

#271 Api: admin/owner-info
  Loopy-fe/src/apis/admin/menu/api.ts
  Loopy-fe/src/apis/admin/photo/type.ts
  Loopy-fe/src/apis/admin/register/stamp/api.ts
  Loopy-fe/src/apis/admin/register/stamp/image/api.ts
  Loopy-fe/src/apis/admin/register/stamp/image/type.ts
  Loopy-fe/src/apis/admin/register/stamp/type.ts
  Loopy-fe/src/apis/admin/setting/photo/api.ts
  Loopy-fe/src/apis/admin/setting/photo/type.ts
  Loopy-fe/src/hooks/mutation/admin/stamp/useCreateStampPolicy.ts
  Loopy-fe/src/hooks/mutation/admin/stamp/useDeleteStampImage.ts
  Loopy-fe/src/hooks/mutation/admin/stamp/useUploadStampImage.ts
  Loopy-fe/src/hooks/query/admin/photo/useCafePhotos.ts
  Loopy-fe/src/hooks/query/admin/stamp/useGetStampImage.ts
  Loopy-fe/src/pages/Admin/Register/_components/AllDayTimeInput.tsx
  Loopy-fe/src/pages/Admin/Register/_components/ModalMenuForm.tsx
  Loopy-fe/src/pages/Admin/Register/_components/TimeSection.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step1DocumentGuide.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step2BasicInfo.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step3BusinessInfo.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step4Menu.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step5Stamp.tsx
  Loopy-fe/src/pages/Admin/Register/index.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/OperationInfoTab.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/basic/BasicInfoFormView.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/basic/PhotoUploader.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/operation/ByDayTimeInput.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/operation/DaySelector.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/operation/TimeSection.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/operation/_logic/useOwnerOperationForm.ts
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/operation/_logic/validators.ts
Labels: fix, api, feat, chore

#273 Api: owner-cafe/cafeId
  Loopy-fe/src/apis/admin/register/document/api.ts
  Loopy-fe/src/apis/admin/register/document/type.ts
  Loopy-fe/src/hooks/mutation/admin/document/useAdminCafe.ts
  Loopy-fe/src/hooks/mutation/detail/useCreateBookmark.ts
  Loopy-fe/src/pages/Admin/Register/_steps/Step1DocumentGuide.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step2BasicInfo.tsx
  Loopy-fe/src/pages/Admin/Register/index.tsx
Labels: api, feat

#275 Api: admin/challenge
  Loopy-fe/src/App.tsx
  Loopy-fe/src/apis/admin/challenge/detail/api.ts
  Loopy-fe/src/apis/alarm/api.ts
  Loopy-fe/src/apis/alarm/type.ts
  Loopy-fe/src/apis/challenge/challengeJoin/api.ts
  Loopy-fe/src/apis/my/alarm/type.ts
  Loopy-fe/src/components/admin/modal/CommonTwoButtonModal.tsx
  Loopy-fe/src/hooks/query/alarm/useNotification.ts
  Loopy-fe/src/hooks/query/challenge/useJoinChallenge.ts
  Loopy-fe/src/hooks/query/my/useMyNotification.ts
  Loopy-fe/src/pages/Admin/Challenge/_components/AdminChallengeDetail.tsx
  Loopy-fe/src/pages/Admin/Challenge/_components/ChallengeCard.tsx
  Loopy-fe/src/pages/Admin/Challenge/_components/ChallengeInfoCard.tsx
  Loopy-fe/src/pages/User/Alarm/index.tsx
  Loopy-fe/src/pages/User/Challenge/components/ChallengeCard.tsx
  Loopy-fe/src/pages/User/Challenge/index.tsx
  Loopy-fe/src/pages/User/ChallengeDetail/ChallengeStoreListPage/index.tsx
  Loopy-fe/src/pages/User/ChallengeDetail/index.tsx
  Loopy-fe/src/pages/User/MyStamp/index.tsx
Labels: api, chore, style

#280 Fix: kakao
  Loopy-fe/src/pages/User/My/Setting/_components/DefaultAccountView.tsx
Labels: fix

#283 Api: home/stamp
  Loopy-fe/src/apis/stampBook/extendStampBook/api.ts
  Loopy-fe/src/apis/stampBook/extendStampBook/type.ts
  Loopy-fe/src/apis/stampBook/stampBookDetail/api.ts
  Loopy-fe/src/apis/stampBook/stampBookDetail/mock.ts
  Loopy-fe/src/apis/stampBook/stampBookDetail/type.ts
  Loopy-fe/src/assets/images/StampDiscount.svg
  Loopy-fe/src/assets/images/StampFree.svg
  Loopy-fe/src/assets/images/StampSizeUp.svg
  Loopy-fe/src/pages/User/MyStamp/components/StampPaper.tsx
  Loopy-fe/src/pages/User/MyStamp/index.tsx
Labels: api, chore

#288 Fix: auth-check
  Loopy-fe/src/App.tsx
  Loopy-fe/src/pages/User/OnBoard/_components/StepCafeInfo.tsx
  Loopy-fe/src/pages/User/Signin/_components/verify/SignupButton.tsx
  Loopy-fe/src/utils/authCheck.ts
  Loopy-fe/src/utils/storage.ts
Labels: fix, setting

#290 Api: owner/cafeStatus
  Loopy-fe/src/apis/admin/cafeStatus/api.ts
  Loopy-fe/src/apis/admin/cafeStatus/type.ts
  Loopy-fe/src/hooks/mutation/admin/cafeStatus/useAdminCafeStatus.ts
  Loopy-fe/src/utils/storage.ts
Labels: fix, feat

#306 Fix: coupon-menus
  Loopy-fe/src/apis/admin/coupon/menu/api.ts
  Loopy-fe/src/apis/admin/coupon/menu/type.ts
  Loopy-fe/src/hooks/query/admin/coupon/useCafeMenus.ts
  Loopy-fe/src/pages/Admin/Coupon/_components/AdminCreateCouponPage.tsx
  Loopy-fe/src/pages/Admin/Coupon/_components/CouponTypeSection.tsx
Labels: fix, style

#309 Fix: auth-check
  Loopy-fe/src/utils/authCheck.ts
Labels: fix

#312 Api: phone-dummy-check
  Loopy-fe/src/apis/auth/phoneCheck/api.ts
  Loopy-fe/src/apis/auth/phoneCheck/type.ts
  Loopy-fe/src/hooks/query/phone/useIsPhoneDummy.ts
  Loopy-fe/src/pages/User/Home/index.tsx
  Loopy-fe/src/pages/auth/LoginSuccess.tsx
  Loopy-fe/src/pages/auth/VerifyPage.tsx
Labels: fix, api, feat

#320 Fix: login/signup-dummy
  Loopy-fe/src/apis/auth/login/api.ts
  Loopy-fe/src/apis/auth/signin/api.ts
Labels: fix, api

#321 Api: save-phone
  Loopy-fe/src/apis/auth/verifyPhone/patch/api.ts
  Loopy-fe/src/apis/auth/verifyPhone/patch/type.ts
  Loopy-fe/src/hooks/mutation/verify/useSavePhone.ts
  Loopy-fe/src/pages/auth/VerifyPage.tsx
Labels: fix, api

#324 Style: 사장님/유저 페이지 디자인 수정
  Loopy-fe/src/assets/images/Home.svg
  Loopy-fe/src/assets/images/HomeFilled.svg
  Loopy-fe/src/assets/images/Level2.svg
  Loopy-fe/src/components/admin/button/CommonAdminButton.tsx
  Loopy-fe/src/components/admin/sideBar/CommonSideBar.tsx
  Loopy-fe/src/components/bottomBar/CommonBottomBar.tsx
  Loopy-fe/src/pages/Admin/Challenge/_components/AdminChallengeList.tsx
  Loopy-fe/src/pages/Admin/Home/_components/AnalysisCard.tsx
  Loopy-fe/src/pages/Admin/Home/_components/ChallengeOverview.tsx
  Loopy-fe/src/pages/Admin/Home/_components/modal/_components/CustomerInfoPanel.tsx
  Loopy-fe/src/pages/Admin/Notification/index.tsx
  Loopy-fe/src/pages/User/ChallengeDetail/index.tsx
  Loopy-fe/src/pages/User/Home/components/ChallangeCard.tsx
Labels: chore, style

#326 Fix: cooldown
  Loopy-fe/src/hooks/usePhoneVerification.ts
  Loopy-fe/src/pages/Admin/Signin/_components/AdminStepPhoneVerify.tsx
  Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepVerify.tsx
  Loopy-fe/src/pages/auth/VerifyPage.tsx
Labels: fix

#328 Fix: 알림받기 및 스탬프 관리 페이지 수정
  Loopy-fe/src/apis/admin/stamp/api.ts
  Loopy-fe/src/apis/admin/stamp/mocks.ts
  Loopy-fe/src/apis/admin/stamp/type.ts
  Loopy-fe/src/apis/cafeDetail/type.ts
  Loopy-fe/src/assets/images/Bookmark-save.svg
  Loopy-fe/src/components/card/EventCard.tsx
  Loopy-fe/src/pages/Admin/Stamp/_components/StampEditDrawer.tsx
  Loopy-fe/src/pages/Admin/Stamp/_components/StampStatsBar.tsx
  Loopy-fe/src/pages/User/Detail/_components/AlarmSubscribeButton.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoPanel.tsx
  Loopy-fe/src/pages/User/Detail/_components/MenuCard.tsx
  Loopy-fe/src/pages/User/Detail/_components/MyStampCard.tsx
  Loopy-fe/src/pages/User/Detail/index.tsx
  Loopy-fe/src/pages/User/Menu/index.tsx
Labels: fix, api

#331 Fix: verify-phone
  Loopy-fe/src/pages/User/Home/index.tsx
  Loopy-fe/src/pages/auth/VerifyPage.tsx
Labels: fix

#333 Fix: cafe-info
  Loopy-fe/src/hooks/action/useAdminHandleLogin.tsx
  Loopy-fe/src/pages/Admin/Register/_steps/Step2BasicInfo.tsx
  Loopy-fe/src/pages/Admin/Setting/_components/tabList/basic/BasicInfoFormView.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminSignupSuccess.tsx
  Loopy-fe/src/pages/Admin/Signin/_components/AdminSinginPage.tsx
  Loopy-fe/src/utils/authCheck.ts
Labels: fix, api

#335 Fix: authcheck
  Loopy-fe/src/utils/authCheck.ts
Labels: fix

#340 Fix: 리뷰 수정
  Loopy-fe/src/pages/User/Detail/_components/BaseModal.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoPanel.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafePhotoModal.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeReviewContent.tsx
  Loopy-fe/src/pages/User/Detail/_components/ReviewButton.tsx
  Loopy-fe/src/pages/User/Detail/_components/ReviewRestrictionModal.tsx
  Loopy-fe/src/pages/User/Detail/_components/TopPhotoSection.tsx
Labels: fix, style

#348 Fix: 지도 페이지 스크롤 막음
  Loopy-fe/src/pages/User/Map/index.tsx
Labels: fix

#349 Api: complete-cafe
  Loopy-fe/src/apis/admin/register/complete/api.ts
  Loopy-fe/src/assets/images/InfoCircle.svg
  Loopy-fe/src/hooks/mutation/admin/complete/useCompleteCafe.ts
  Loopy-fe/src/pages/Admin/Register/_steps/Step5Stamp.tsx
  Loopy-fe/src/pages/User/My/CouponBox/index.tsx
Labels: api, feat

#350 fix: 리뷰 필드명 수정
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoPanel.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeReviewContent.tsx
  Loopy-fe/src/pages/User/Search/index.tsx
Labels: fix, api

#351 Fix: coupon-toggle
  Loopy-fe/src/pages/User/My/CouponBox/index.tsx
Labels: fix

#352 Api: 인사이트 연결 및 자잘한 수정
  Loopy-fe/src/apis/admin/home/insight/api.ts
  Loopy-fe/src/apis/admin/home/insight/type.ts
  Loopy-fe/src/assets/images/BellWhite.svg
  Loopy-fe/src/hooks/query/admin/home/useInsight.ts
  Loopy-fe/src/pages/Admin/Home/_components/AnalysisCard.tsx
  Loopy-fe/src/pages/Admin/Home/_components/modal/InsightModal.tsx
  Loopy-fe/src/pages/Admin/Home/index.tsx
  Loopy-fe/src/pages/User/Challenge/components/ChallengeTab.tsx
  Loopy-fe/src/pages/User/ChallengeDetail/index.tsx
  Loopy-fe/src/pages/User/Home/components/TopBar.tsx
  Loopy-fe/src/pages/User/MyStamp/index.tsx
Labels: api, chore

#353 Fix: 리뷰 카페 제목 불러오기
  Loopy-fe/src/pages/User/Detail/_components/ReviewButton.tsx
  Loopy-fe/src/pages/User/Detail/index.tsx
  Loopy-fe/src/pages/User/Review/index.tsx
Labels: chore

#356 Fix/search map detail
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoContent.tsx
  Loopy-fe/src/pages/User/Detail/_components/CafeInfoPanel.tsx
  Loopy-fe/src/pages/User/Detail/_components/MyStampCard.tsx
  Loopy-fe/src/pages/User/Detail/index.tsx
Labels: chore, style

#358 Fix: stamp-history/api
  Loopy-fe/src/apis/my/converted/api.ts
  Loopy-fe/src/apis/my/converted/mock.ts
  Loopy-fe/src/apis/my/converted/type.ts
  Loopy-fe/src/hooks/query/my/useConvertedStamp.ts
  Loopy-fe/src/pages/User/My/StampHistory/_components/CompletedStampDetailPage.tsx
  Loopy-fe/src/pages/User/My/StampHistory/_components/StampHistoryItem.tsx
  Loopy-fe/src/pages/User/My/StampHistory/index.tsx
Labels: fix, api

#360 Fix: mypage
  Loopy-fe/src/pages/User/My/index.tsx
Labels: fix

#364 Fix: mypage-refetch
  Loopy-fe/src/hooks/query/userInfo/useMyInfo.ts
  Loopy-fe/src/pages/User/My/Setting/index.tsx
  Loopy-fe/src/pages/User/My/_components/ProfileSection.tsx
Labels: fix, api

#366 Fix: exchange-api
  Loopy-fe/src/apis/my/exchange/api.ts
  Loopy-fe/src/apis/my/exchange/type.ts
  Loopy-fe/src/hooks/mutation/my/exchange/useConvertStampBook.ts
  Loopy-fe/src/pages/User/My/StampExchange/_components/ActiveStampDetailPage.tsx
  Loopy-fe/src/pages/User/My/StampExchange/index.tsx
Labels: fix, api, feat

#367 Chore: qr
  Loopy-fe/src/pages/User/My/_components/QrPopup.tsx
Labels: chore
